---
name: Bug Report
description: File a bug report.
title: "[BUG]: <...>"
labels:
  - BUG
body:
  - type: checkboxes
    attributes:
      label: Terms
      description: By submitting this issue, you agree to the terms.
      options:
        - label: I agree to follow this project's code of conduct.
          required: true
        - label: I confirm that the same issue has not been submitted yet.
          required: true
  - type: textarea
    attributes:
      label: What happened?
      description: Describe in detail what the bug is.
      render: markdown
      placeholder: |
        * What is the context?
        * Under what conditions does the bug appear?
        * What is the expected behavior?
    validations:
      required: true
  - type: textarea
    attributes:
      label: How to Reproduce?
      description: Describe how to reproduce the bug.
      render: markdown
      placeholder: |
        1. Write such and such text to a file...
        2. Run the command: `bull-terrier ...`
        3. ...
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Bull-Terrier Version
      description: What version of the software are you running?
      options:
        - Bull-Terrier 0.0.0
        - Other (Use the Comments)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Operating System
      description: Which operating system is used?
      render: markdown
      placeholder: <...>
    validations:
      required: true
  - type: textarea
    attributes:
      label: Comments
      description: Links? References? Something else?
      render: markdown
      placeholder: <...>
    validations:
      required: false
